# Generated by Django 4.1.3 on 2023-04-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('subjects', models.CharField(choices=[('MATHS', 'MATHS'), ('SCIENCE', 'SCIENCE'), ('HISTORY', 'HISTORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('LANGUAGE', 'LANGUAGE')], max_length=300)),
                ('standard', models.CharField(choices=[('KINDERGARDEN', 'KINDERGARDEN'), ('CLASS-1 TO CLASS-5', 'CLASS-1 TO CLASS-5'), ('CLASS-6 TO CLASS-10', 'CLASS-6 TO CLASS-10'), ('CLASS 11-12', 'CLASS 11-12')], max_length=100)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('standard', models.CharField(choices=[('KINDERGARDEN', 'KINDERGARDEN'), ('CLASS-1 TO CLASS-5', 'CLASS-1 TO CLASS-5'), ('CLASS-6 TO CLASS-10', 'CLASS-6 TO CLASS-10'), ('CLASS 11-12', 'CLASS 11-12')], max_length=100)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
